os:
  - linux
language: rust
rust:
  - stable
cache:
  - apt
matrix:
  include:
    - env:
      - NAME=facere
      - TARGET=arm-unknown-linux-gnueabihf
      - LINKER=arm-linux-gnueabihf-gcc
      - PACKAGE=$NAME-rpi2.tar.gz
    addons:
        apt:
          packages: &armhf
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - env:
      - NAME=facere
      - TARGET=armv7-unknown-linux-gnueabihf
      - LINKER=arm-linux-gnueabihf-gcc
      - PACKAGE=$NAME-rpi3.tar.gz
    addons:
      apt:
        packages: *armhf
    - env:
      - NAME=facere
      - TARGET=i686-unknown-linux-gnu
      - PACKAGE=$NAME-i686.tar.gz
    addons:
      apt:
        packages:
          - gcc-multilib
    - env:
      - NAME=facere
      - TARGET=x86_64-unknown-linux-gnu
      - PACKAGE=$NAME-x86_64.tar.gz

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add $TARGET || true
  - |
    if [ -n "$LINKER" ]; then
      mkdir -p ~/.cargo
      echo >> ~/.cargo/config
      echo "[target.$TARGET]" >> ~/.cargo/config
      echo "linker = \"$LINKER\"" >> ~/.cargo/config
    fi

script:
  - |
    if [ $TARGET = "x86_64-unknown-linux-gnu" ]; then
      cargo test
    fi
  - cargo build --target $TARGET --verbose --release

before_deploy:
  - tar -czf $PACKAGE -C target/$TARGET/release/ $NAME

deploy:
deploy:
  provider: releases
  api_key:
    secure: d9bgrslzLJGsNOauUlpqj+L8iEB4fc1NyDOTT1iqSMZP9k/+xDCPUWyVveYB3HdIWyIgt9wEMeuKurBvbzHTxpJbWePOm8eqlN5Utigq379o/tQixZVtlmXTct3DzTPYDIfdKJRe5wS83nB4Jjs6U7l4To+SQGmFUQciBfskJNDDikcxr1EqFkKDsMN89GSnzEMhEdLhuXDaDk1HyE9hQOCRl7S1ADwcsfPffNBDUaCNJH53OB8mL5XQqQx6agWSE1SrIeJYXULwAnZzp1WA1U++pcuehEW+QnvIR3RyEie3+OGfJKFbXhWlHtLUV1WHX0tTrUZB6/UsJ1bqrCfyzrWVcb4OZVd5aTD6vOsB6q4qaT4H9Y7A3+woJqJwfnvifJB+fOAV7VABBBA2Kf8YRyqWgd2Sj9qc17WHJpoOVrdBemBzth/OE2rJtp7zGPnaIIVNDdT7Mn7fXptkDszfrCNEkWS+zSQANvCP0EntCTuuC766R+RzQbSbRKLJvB2ubAQzUIaeS9LUatn4eiZUWPGgyvd4aHbTUejiC5CCj9cfL9uDJiDsEn4Oq7olv3xTNriLwjw7HFB2Os0Uq/6Y7qO0aJeIwliVFwK6XxBdFnAY5fXUWN7Ccen8N6PqLrziLT+A6hK60mfP1yAKIeSItAb3a29ae7BvlllKtr510fc=
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
    repo: facere

branches:
only:
  # release tags
  - /^v\d+\.\d+\.\d+.*$/
  - main