os:
  - linux
language: rust
rust:
  - stable
cache:
  - apt
matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add $TARGET || true
  - |
    if [ -n "$LINKER" ]; then
      mkdir -p ~/.cargo
      echo >> ~/.cargo/config
      echo "[target.$TARGET]" >> ~/.cargo/config
      echo "linker = \"$LINKER\"" >> ~/.cargo/config
    fi

script:
  - |
    if [ $TARGET = "x86_64-unknown-linux-gnu" ]; then
      cargo test
    fi
  - cargo build --target $TARGET --verbose --release

before_deploy:
  - tar -czf $PACKAGE -C target/$TARGET/release/ $NAME

deploy:
  provider: releases
  api_key:
    secure: KqFzLfzB3Ym4HH8X5Uf9kAuhOpwIvgLOUzb9qRNpxARZtOvz0TAJfjCjcJasLyjPXfg2suVNNiqrjz8Q7kQfx6/fPwTBxcBge9tVG5IEKr6Adl5YIVzlj374OsXP8vBVQcgC20cfEAqsX3KS113PMSblvMtFeLRLZgRHopajnb3+ymxO+vZbe9auaecbhZECiV2SLWSaZqnfV9iXgYMNfjz0PH7BPJlNSwshP7hWBMjd3OSd8ZDkn1XMOgsb7AcwlHSvtKSdkEPYQI0hRbTFri1BjhFcMnHLkx5ZaPRZ0FR1xCIDNAtr3Zp1OgC5BEvnXFWMHCL/dsGruulY+Lp/vObQ3X5pkDRB6PDNXQkCEeBntqHdxgRa3cMX3PhqNLgnnOZsusao8lg6m/L2v3vuxwvzm0ACt3tVhYxH5Xl6mBM+b/JK8t6tR0P3EcwxaUAg95GJcyVTNpaW1ioy2zkTVddriKPeMJ+tR6dp9rEgSNg1D2blRxjgTIWFay3iAhI7WxjS5re2HV7tqsPiTXeKZbh9YSCXWrQxU8LnYvcnYirE1Yfc68r3IIStstJ9kmStcCBCxPol6QP8/dguszFdpGBOIfzqUNID6chg+W6nbyBLnrqJ9+H+3AEXqj0zVjTIVN8eIzcyfhmdd9w26YN0Xkz3dPsvn+ND4nTtelzPmFA=
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
    repo: facere

branches:
only:
  # release tags
  - /^v\d+\.\d+\.\d+.*$/
  - main